### ISSUE TITLE
AvailabilityTest function

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/TopcomInterface#3]
https://github.com/homalg-project/TopcomInterface/blob/d58ff9312dd035878b676391077a858379342a88/PackageInfo.g#L77-L80

I would suggest adjusting the package availability test to return true only if the required binary files are available on the system. Take a look at
https://github.com/homalg-project/homalg_project/blob/31ec97bebc0d0e056a56ef1f593f58761c3466a3/4ti2Interface/PackageInfo.g#L72

**Comment by HereAround** [comment]
Thank you Kamal. I propose a fix at https://github.com/homalg-project/TopcomInterface/pull/5.
